version: "3.9"

services:
  java17:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - ./workspace:/workspace
    tty: true
    stdin_open: true
    command: tail -f /dev/null